http:
  routers:
    auth:
      rule: "Host(`api.applik-ni.com`) && PathPrefix(`/api/v1/auth`)"
      entryPoints:
        - websecure
      service: auth-service
      tls:
        certResolver: myresolver

    job:
      rule: "Host(`api.applik-ni.com`) && PathPrefix(`/api/v1/jobs`)"
      entryPoints:
        - websecure
      service: job-service
      tls:
        certResolver: myresolver

    talent:
      rule: "Host(`api.applik-ni.com`) && PathPrefix(`/api/v1/talents`)"
      entryPoints:
        - websecure
      service: talent-service
      tls:
        certResolver: myresolver

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:3002"

    job-service:
      loadBalancer:
        servers:
          - url: "http://job-service:3003"

    talent-service:
      loadBalancer:
        servers:
          - url: "http://talent-service:3002"
